# -*- coding: utf-8 -*-
"""24_aug_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12guhQLbWzlN1axP5moIbA3__MqizaFy4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

celcius = np.array([-40,-10,0,8,15,22,38])

celcius

farenhest = np.array([-40,14,32,46,59,72,100])

farenhest

plt.scatter(celcius,farenhest)
plt.xlabel('celcius ---> Independent')
plt.ylabel('farenhest ---> Dependent')
plt.show()

import statsmodels .api as sm

celcius

x1 = sm.add_constant(celcius)

x1

model = sm.OLS(farenhest,x1).fit()

model.summary()

y_hat = 31.9525+1.7979*-x1

y_hat

plt.scatter(celcius,farenhest)
plt.plot(celcius,y_hat,color='red')
plt.xlabel('celcius ---> Independent')
plt.ylabel('farenhest ---> Dependent')
plt.show()

model.predict([1.0,3.5])

model.predict([1.0,10])

y_hat = 31.9525+1.7979*-x1

y_hat

plt.scatter(celcius,farenhest)
plt.plot(celcius,y_hat,color='red')
plt.xlabel('celcius ---> Independent')
plt.ylabel('farenhest ---> Dependent')
plt.show()













